'use strict';

import { jqueryselectBox } from './lib/jquery.selectBox.js';

import { megamenu } from './modules/megamenu.js';
import { menu } from './modules/menu.js';
import { modal } from './modules/modal.js';
import { search } from './modules/search.js';
import { iframe } from './modules/iframe.js';
import { myslick } from './modules/customSlick.js';
import { tombstoneSlick } from './modules/tombstoneSlick.js';
import { share } from './modules/share.js';
import { selectBox } from './modules/selectBox.js';
import { magnificPopup } from './modules/magnificPopup.js';
import { uiAccordion } from './modules/accordion.js';
import { gsapanim } from './modules/gsap.js';
import { counter } from './modules/counter.js';
import { gsapscroll } from './modules/gsapscroll.js';
import Scroll from './modules/scroll';
import { sticky } from './modules/stickySidebar.js';
import { stickyYear } from './modules/stickyYear.js';
import { servicestickyYear } from './modules/serviceStickYear.js';
import { sidebyside } from './modules/sidebyside.js';
import { retired } from './modules/retired.js';
import { feeSchedule } from './modules/feeSchedule.js';
import { reports } from './modules/reports.js';
import { resforms } from './modules/resource-form.js';
import { resource } from './modules/resource.js';
import { resourcecategory } from './modules/resourcecategory.js';
import { serviceTierTombstones } from './modules/service-tier-3-tombstones.js';
import { managementHover } from './modules/managementhover.js';
import { uicategory } from './modules/uicategory.js';
import { jumpto } from './modules/jumpto.js';
import { servicetierfunddetails } from './modules/servicetierfunddetails.js';
import { inputNumber } from './modules/inputNumber.js';
import { notification } from './modules/notification.js';

document.addEventListener('DOMContentLoaded', function () {
  // (function () {
  megamenu.init();
  menu.init();
  modal.init();
  search.init();
  iframe.init();
  myslick.init();
  tombstoneSlick.init();
  share.init();
  jqueryselectBox.init();
  selectBox.init();
  magnificPopup.init();
  uiAccordion.init();
  gsapanim.init();
  counter.init();
  gsapscroll.init();
  sticky.init();
  stickyYear.init();
  servicestickyYear.init();
  sidebyside.init();
  retired.init();
  feeSchedule.init();
  reports.init();
  resforms.init();
  serviceTierTombstones.tier();
  managementHover.me();
  resource.init();
  resourcecategory.init();
  uicategory.init();
  jumpto.init();
  servicetierfunddetails.fund();
  inputNumber.input();
  notification.init();
  // })();
});
let scrolled = window.scrollY;
window.addEventListener('scroll', function () {
  scrolled = window.scrollY;
  Scroll.handle(scrolled);
  gsapscroll.handle(scrolled, Scroll.direction);
});
